version: "3.8"

services:
  app:
    build: .
    container_name: auction_php
    ports:
      - "8085:80"  # Changed from 8080 to 8085 to avoid conflicts
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7  # Using MySQL 5.7
    container_name: auction_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auction_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Changed from 3306 to 3307 to avoid conflicts
    volumes:
      - db_data:/var/lib/mysql
      - ../shop.sql:/docker-entrypoint-initdb.d/shop.sql  # Auto-import SQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: auction_phpmyadmin
    restart: always
    ports:
      - "8086:80"  # Changed from 8081 to 8086 to avoid conflicts
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
